// Code generated by protoc-gen-go. DO NOT EDIT.
// source: progress_service.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NewProgressBarRequest struct {
	StartingProgress uint32 `protobuf:"varint,1,opt,name=startingProgress" json:"startingProgress,omitempty"`
}

func (m *NewProgressBarRequest) Reset()                    { *m = NewProgressBarRequest{} }
func (m *NewProgressBarRequest) String() string            { return proto.CompactTextString(m) }
func (*NewProgressBarRequest) ProtoMessage()               {}
func (*NewProgressBarRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *NewProgressBarRequest) GetStartingProgress() uint32 {
	if m != nil {
		return m.StartingProgress
	}
	return 0
}

type NewProgressBarResponse struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *NewProgressBarResponse) Reset()                    { *m = NewProgressBarResponse{} }
func (m *NewProgressBarResponse) String() string            { return proto.CompactTextString(m) }
func (*NewProgressBarResponse) ProtoMessage()               {}
func (*NewProgressBarResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *NewProgressBarResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewProgressBarResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ProgressBarStatusRequest struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *ProgressBarStatusRequest) Reset()                    { *m = ProgressBarStatusRequest{} }
func (m *ProgressBarStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*ProgressBarStatusRequest) ProtoMessage()               {}
func (*ProgressBarStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ProgressBarStatusRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ProgressBarStatusResponse struct {
	ProgressBars []*ProgressBar `protobuf:"bytes,1,rep,name=progressBars" json:"progressBars,omitempty"`
}

func (m *ProgressBarStatusResponse) Reset()                    { *m = ProgressBarStatusResponse{} }
func (m *ProgressBarStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*ProgressBarStatusResponse) ProtoMessage()               {}
func (*ProgressBarStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ProgressBarStatusResponse) GetProgressBars() []*ProgressBar {
	if m != nil {
		return m.ProgressBars
	}
	return nil
}

type UpdateProgressBarRequest struct {
	Id               string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Token            string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	NewProgressValue uint32 `protobuf:"varint,3,opt,name=newProgressValue" json:"newProgressValue,omitempty"`
}

func (m *UpdateProgressBarRequest) Reset()                    { *m = UpdateProgressBarRequest{} }
func (m *UpdateProgressBarRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProgressBarRequest) ProtoMessage()               {}
func (*UpdateProgressBarRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *UpdateProgressBarRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateProgressBarRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateProgressBarRequest) GetNewProgressValue() uint32 {
	if m != nil {
		return m.NewProgressValue
	}
	return 0
}

type UpdateProgressBarResponse struct {
	Id               string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Token            string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	NewProgressValue uint32 `protobuf:"varint,3,opt,name=newProgressValue" json:"newProgressValue,omitempty"`
}

func (m *UpdateProgressBarResponse) Reset()                    { *m = UpdateProgressBarResponse{} }
func (m *UpdateProgressBarResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateProgressBarResponse) ProtoMessage()               {}
func (*UpdateProgressBarResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *UpdateProgressBarResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateProgressBarResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateProgressBarResponse) GetNewProgressValue() uint32 {
	if m != nil {
		return m.NewProgressValue
	}
	return 0
}

func init() {
	proto.RegisterType((*NewProgressBarRequest)(nil), "pb.NewProgressBarRequest")
	proto.RegisterType((*NewProgressBarResponse)(nil), "pb.NewProgressBarResponse")
	proto.RegisterType((*ProgressBarStatusRequest)(nil), "pb.ProgressBarStatusRequest")
	proto.RegisterType((*ProgressBarStatusResponse)(nil), "pb.ProgressBarStatusResponse")
	proto.RegisterType((*UpdateProgressBarRequest)(nil), "pb.UpdateProgressBarRequest")
	proto.RegisterType((*UpdateProgressBarResponse)(nil), "pb.UpdateProgressBarResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProgressBarService service

type ProgressBarServiceClient interface {
	NewProgressBar(ctx context.Context, in *NewProgressBarRequest, opts ...grpc.CallOption) (*NewProgressBarResponse, error)
	GetProgressBarStatus(ctx context.Context, in *ProgressBarStatusRequest, opts ...grpc.CallOption) (*ProgressBarStatusResponse, error)
	UpdateProgressBar(ctx context.Context, in *UpdateProgressBarRequest, opts ...grpc.CallOption) (*UpdateProgressBarResponse, error)
	DeleteProgressBar(ctx context.Context, in *ProgressBarStatusRequest, opts ...grpc.CallOption) (*ProgressBarStatusResponse, error)
}

type progressBarServiceClient struct {
	cc *grpc.ClientConn
}

func NewProgressBarServiceClient(cc *grpc.ClientConn) ProgressBarServiceClient {
	return &progressBarServiceClient{cc}
}

func (c *progressBarServiceClient) NewProgressBar(ctx context.Context, in *NewProgressBarRequest, opts ...grpc.CallOption) (*NewProgressBarResponse, error) {
	out := new(NewProgressBarResponse)
	err := grpc.Invoke(ctx, "/pb.ProgressBarService/NewProgressBar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressBarServiceClient) GetProgressBarStatus(ctx context.Context, in *ProgressBarStatusRequest, opts ...grpc.CallOption) (*ProgressBarStatusResponse, error) {
	out := new(ProgressBarStatusResponse)
	err := grpc.Invoke(ctx, "/pb.ProgressBarService/GetProgressBarStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressBarServiceClient) UpdateProgressBar(ctx context.Context, in *UpdateProgressBarRequest, opts ...grpc.CallOption) (*UpdateProgressBarResponse, error) {
	out := new(UpdateProgressBarResponse)
	err := grpc.Invoke(ctx, "/pb.ProgressBarService/UpdateProgressBar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressBarServiceClient) DeleteProgressBar(ctx context.Context, in *ProgressBarStatusRequest, opts ...grpc.CallOption) (*ProgressBarStatusResponse, error) {
	out := new(ProgressBarStatusResponse)
	err := grpc.Invoke(ctx, "/pb.ProgressBarService/DeleteProgressBar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProgressBarService service

type ProgressBarServiceServer interface {
	NewProgressBar(context.Context, *NewProgressBarRequest) (*NewProgressBarResponse, error)
	GetProgressBarStatus(context.Context, *ProgressBarStatusRequest) (*ProgressBarStatusResponse, error)
	UpdateProgressBar(context.Context, *UpdateProgressBarRequest) (*UpdateProgressBarResponse, error)
	DeleteProgressBar(context.Context, *ProgressBarStatusRequest) (*ProgressBarStatusResponse, error)
}

func RegisterProgressBarServiceServer(s *grpc.Server, srv ProgressBarServiceServer) {
	s.RegisterService(&_ProgressBarService_serviceDesc, srv)
}

func _ProgressBarService_NewProgressBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewProgressBarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressBarServiceServer).NewProgressBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ProgressBarService/NewProgressBar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressBarServiceServer).NewProgressBar(ctx, req.(*NewProgressBarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressBarService_GetProgressBarStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressBarStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressBarServiceServer).GetProgressBarStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ProgressBarService/GetProgressBarStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressBarServiceServer).GetProgressBarStatus(ctx, req.(*ProgressBarStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressBarService_UpdateProgressBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProgressBarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressBarServiceServer).UpdateProgressBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ProgressBarService/UpdateProgressBar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressBarServiceServer).UpdateProgressBar(ctx, req.(*UpdateProgressBarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressBarService_DeleteProgressBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressBarStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressBarServiceServer).DeleteProgressBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ProgressBarService/DeleteProgressBar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressBarServiceServer).DeleteProgressBar(ctx, req.(*ProgressBarStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProgressBarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ProgressBarService",
	HandlerType: (*ProgressBarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewProgressBar",
			Handler:    _ProgressBarService_NewProgressBar_Handler,
		},
		{
			MethodName: "GetProgressBarStatus",
			Handler:    _ProgressBarService_GetProgressBarStatus_Handler,
		},
		{
			MethodName: "UpdateProgressBar",
			Handler:    _ProgressBarService_UpdateProgressBar_Handler,
		},
		{
			MethodName: "DeleteProgressBar",
			Handler:    _ProgressBarService_DeleteProgressBar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "progress_service.proto",
}

func init() { proto.RegisterFile("progress_service.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0x53, 0x1a, 0x4d, 0x3a, 0x2a, 0xb6, 0x9b, 0xda, 0x00, 0xd1, 0xc4, 0xec, 0xa9, 0x31,
	0x86, 0x43, 0x7b, 0xf7, 0xa0, 0x26, 0xbd, 0x19, 0x42, 0xa3, 0x57, 0x03, 0x32, 0x69, 0x88, 0x08,
	0xeb, 0xee, 0xa2, 0xdf, 0xd4, 0xcf, 0x63, 0x60, 0x21, 0xe5, 0xcf, 0x92, 0x58, 0x6f, 0xf0, 0xde,
	0xce, 0x9b, 0xe1, 0x37, 0x0b, 0x2c, 0x18, 0xcf, 0x76, 0x1c, 0x85, 0x78, 0x15, 0xc8, 0xbf, 0xe2,
	0x37, 0x74, 0x19, 0xcf, 0x64, 0x46, 0x0c, 0x16, 0x3a, 0x66, 0xed, 0x29, 0x8d, 0x3e, 0xc0, 0xc5,
	0x13, 0x7e, 0x7b, 0x95, 0x78, 0x1f, 0x70, 0x1f, 0x3f, 0x73, 0x14, 0x92, 0xdc, 0xc0, 0x54, 0xc8,
	0x80, 0xcb, 0x38, 0xdd, 0xd5, 0xae, 0x35, 0xba, 0x1e, 0x2d, 0xcf, 0xfc, 0x9e, 0x4e, 0xef, 0x60,
	0xd1, 0x0d, 0x11, 0x2c, 0x4b, 0x05, 0x12, 0x13, 0x8c, 0x38, 0x2a, 0xeb, 0x26, 0xbe, 0x11, 0x47,
	0x64, 0x0e, 0x47, 0x32, 0x7b, 0xc7, 0xd4, 0x32, 0x4a, 0x49, 0xbd, 0xd0, 0x5b, 0xb0, 0x1a, 0xc5,
	0x5b, 0x19, 0xc8, 0x5c, 0xd4, 0x73, 0x4c, 0x61, 0x1c, 0x47, 0x45, 0xeb, 0xf1, 0x72, 0xe2, 0x17,
	0x8f, 0xd4, 0x03, 0x5b, 0x73, 0xba, 0x6a, 0xb8, 0x86, 0x53, 0xb6, 0x37, 0x55, 0xdd, 0xc9, 0xea,
	0xdc, 0x65, 0xa1, 0xdb, 0x9c, 0xaf, 0x75, 0x88, 0x26, 0x60, 0x3d, 0xb3, 0x28, 0x90, 0xa8, 0xe1,
	0xf0, 0xa7, 0x2f, 0x28, 0x68, 0xa5, 0x7b, 0x02, 0x2f, 0x41, 0x92, 0xa3, 0x35, 0x56, 0xb4, 0xba,
	0x3a, 0xfd, 0x00, 0x5b, 0xd3, 0xed, 0x10, 0x60, 0x87, 0xb4, 0x5b, 0xfd, 0x18, 0x40, 0x9a, 0xbc,
	0xd4, 0x95, 0x20, 0x1b, 0x30, 0xdb, 0x3b, 0x23, 0x76, 0x01, 0x49, 0x7b, 0x19, 0x1c, 0x47, 0x67,
	0x55, 0x13, 0x6f, 0x61, 0xbe, 0x41, 0xd9, 0xdb, 0x08, 0xb9, 0xec, 0x30, 0x6f, 0xad, 0xd5, 0xb9,
	0x1a, 0x70, 0xab, 0x50, 0x0f, 0x66, 0x3d, 0x46, 0x2a, 0x71, 0x68, 0x51, 0x2a, 0x71, 0x18, 0xac,
	0x07, 0xb3, 0x47, 0x4c, 0x50, 0x93, 0xf8, 0xcf, 0x19, 0xc3, 0xe3, 0xf2, 0x0f, 0x5a, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x91, 0x2f, 0x4e, 0xc8, 0x6f, 0x03, 0x00, 0x00,
}
