// Code generated by protoc-gen-go.
// source: progress.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	progress.proto
	progress_service.proto

It has these top-level messages:
	ProgressBar
	NewProgressBarRequest
	NewProgressBarResponse
	ProgressBarStatusRequest
	ProgressBarStatusResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProgressBar struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Progress uint32 `protobuf:"varint,2,opt,name=progress" json:"progress,omitempty"`
}

func (m *ProgressBar) Reset()                    { *m = ProgressBar{} }
func (m *ProgressBar) String() string            { return proto.CompactTextString(m) }
func (*ProgressBar) ProtoMessage()               {}
func (*ProgressBar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProgressBar) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProgressBar) GetProgress() uint32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func init() {
	proto.RegisterType((*ProgressBar)(nil), "pb.ProgressBar")
}

func init() { proto.RegisterFile("progress.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x4f,
	0x2f, 0x4a, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xb2,
	0xe4, 0xe2, 0x0e, 0x80, 0x8a, 0x3a, 0x25, 0x16, 0x09, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x49, 0x71, 0x71, 0xc0, 0x34, 0x49, 0x30,
	0x29, 0x30, 0x6a, 0xf0, 0x06, 0xc1, 0xf9, 0x49, 0x6c, 0x60, 0x53, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xb1, 0x85, 0xcb, 0x1e, 0x57, 0x00, 0x00, 0x00,
}
